# The URL the site will be built forf
base_url = "https://tgmatos.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "no-style-please"

[markdown.highlighting]
style = "inline"
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
# Put all your custom variables here
header_nav = [
    { name = "Github", url = "https://github.com/tgmatos" },
    { name = "~home", url = "/" },
    { name = "Linkedin", url = "https://www.linkedin.com/in/tiago-matos-314204289/" },
]
